# **Credit Risk Model Data Analysis Project** 

In [1]:
# Author: Gallant Captain
# Date: August 08, 2024

**Note 1:**
* Our goal is to obtain a clean & preprocessed dataset
* We'll note down the changes we're making to the original dataset
* This information will be invaluable to the data scientists

**Note 2:**
1. Every categorical variable must be quantified.
2. We need to change any text columns into numbers (Based on info).
3. For others, we only care if they provide +ve or -ve connotations.

**Note 3: Measuring Creditworthiness**
* We need to be extremely risk-averse & distrustful.
* Missing information suggests foul play.
* If information isn't available, assume the worst.

In [2]:
import numpy as np

In [3]:
np.set_printoptions(suppress= True, linewidth= 100, precision= 2)

### **Importing the Data**

In [4]:
#Import the Loan Data file, delimiter ';', encoding 'windows-1251'.
file_location_1="loan-data.csv"
raw_data_np= np.genfromtxt(file_location_1, delimiter= ";", encoding= "windows-1251")
print(raw_data_np)

[[        nan         nan         nan ...         nan         nan         nan]
 [48010226.           nan    35000.   ...         nan         nan     9452.96]
 [57693261.           nan    30000.   ...         nan         nan     4679.7 ]
 ...
 [50415990.           nan    10000.   ...         nan         nan     2185.64]
 [46154151.           nan         nan ...         nan         nan     3199.4 ]
 [66055249.           nan    10000.   ...         nan         nan      301.9 ]]


In [5]:
#Best practices code, use skipheader & autostrip 
raw_data_np= np.genfromtxt(file_location_1, delimiter= ";", encoding= "windows-1251",
                           skip_header= 1, autostrip= True)
print(raw_data_np) #Now data looks much cleaner & clearer

[[48010226.           nan    35000.   ...         nan         nan     9452.96]
 [57693261.           nan    30000.   ...         nan         nan     4679.7 ]
 [59432726.           nan    15000.   ...         nan         nan     1969.83]
 ...
 [50415990.           nan    10000.   ...         nan         nan     2185.64]
 [46154151.           nan         nan ...         nan         nan     3199.4 ]
 [66055249.           nan    10000.   ...         nan         nan      301.9 ]]


### **Checking for Incomplete Data**

In [6]:
#Check for NAN values by calling np.isnan & use .sum() to check how many NAN values.
np.isnan(raw_data_np).sum() #88005 NAN values as NAN is True (1)

88005

In [7]:
#Create 2 temporary variables to handle the missing data
temporary_fill= np.nanmax(raw_data_np) + 1 #A filler for all the missing entries of the dataset
temporary_mean= np.nanmean(raw_data_np, axis= 0) #Hold the means for every column
#Get the max value & mean value of the dataset
#RuntimeWarning: Mean of empty slice (temporary_mean) - This means that there is atleast 1 empty column with NAN values.

C:\Users\avira\AppData\Local\Temp\ipykernel_9564\3925349410.py:3: RuntimeWarning: Mean of empty slice
  temporary_mean= np.nanmean(raw_data_np, axis= 0) #Hold the means for every column


In [8]:
#Verify the NAN warnings of the variable. 8 columns have NAN values.
temporary_mean #Here, 'NAN mean' values means the columns only store strings.

array([54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
            440.92,         nan,         nan,         nan,         nan,         nan,     3143.85])

In [9]:
#Fill out the missing variables of the missing columns
temporary_stats= np.array([np.nanmin(raw_data_np, axis= 0),
                                     temporary_mean,
                                     np.nanmax(raw_data_np, axis= 0)])

C:\Users\avira\AppData\Local\Temp\ipykernel_9564\3027522355.py:2: RuntimeWarning: All-NaN slice encountered
  temporary_stats= np.array([np.nanmin(raw_data_np, axis= 0),
C:\Users\avira\AppData\Local\Temp\ipykernel_9564\3027522355.py:4: RuntimeWarning: All-NaN slice encountered
  np.nanmax(raw_data_np, axis= 0)])


In [10]:
#Now print the filled out values
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

### **Splitting the Dataset**

To split the data between which contains numerical and categorical data.

#### ***Splitting the Columns***
By splitting we can then use usecols = .....

In [11]:
#If value 1 = 0. Column contains only text -> mean= NAN. np.isnan returns True for that column.
columns_strings= np.argwhere(np.isnan(temporary_mean)).squeeze() 
columns_strings #Since True != 0, np.argwhere() returns the index 

array([ 1,  3,  5,  8,  9, 10, 11, 12], dtype=int64)

In [12]:
#Which columns contain numeric values. Columns that don't contain NAN values != NAN. np.isnan returns False for that column.
columns_numeric= np.argwhere(np.isnan(temporary_mean) == False).squeeze() #,squeeze to return 1-D array
columns_numeric #Since, False == 0, np.argwhere() returns the index of numericals

array([ 0,  2,  4,  6,  7, 13], dtype=int64)

#### ***Re-Importing the Dataset***

In [13]:
#Split to String Dataset
#Reimport dataset for string values and use skipheader & autostrip: Strips whitespace characters leading/trailing 
loan_data_strings= np.genfromtxt(file_location_1, delimiter= ";", encoding= "windows-1251",
                                 skip_header= 1, autostrip= True, dtype= np.str_,
                                 usecols= columns_strings)
print(loan_data_strings) #Now data is split for text values & looks much cleaner & clearer

[['May-15' 'Current' '36 months' ... 'Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226' 'CA']
 ['' 'Current' '36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261' 'NY']
 ['Sep-15' 'Current' '36 months' ... 'Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726' 'PA']
 ...
 ['Jun-15' 'Current' '36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990' 'CA']
 ['Apr-15' 'Current' '36 months' ... 'Source Verified'
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151' 'OH']
 ['Dec-15' 'Current' '36 months' ... ''
  'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249' 'IL']]


In [14]:
#Split to numeric dataset
#Reimport dataset for numerical values and use skipheader & autostrip: Strips whitespace characters leading/trailing 
loan_data_numeric= np.genfromtxt(file_location_1, delimiter= ";", encoding= "windows-1251",
                                 skip_header= 1, autostrip= True, usecols= columns_numeric,
                                 filling_values= temporary_fill)
print(loan_data_numeric) #Now data is split for numerical values & looks much cleaner & clearer
#We use filling values here as numerical NAN values will be handled differently than the text ones.

[[48010226.      35000.      35000.         13.33     1184.86     9452.96]
 [57693261.      30000.      30000.   68616520.        938.57     4679.7 ]
 [59432726.      15000.      15000.   68616520.        494.86     1969.83]
 ...
 [50415990.      10000.      10000.   68616520.   68616520.       2185.64]
 [46154151.   68616520.      10000.         16.55      354.3      3199.4 ]
 [66055249.      10000.      10000.   68616520.        309.97      301.9 ]]


***Tips:**
* We have successfully split the data into two types: Numerical and String type datasets for better analytics.

#### ***The Names of the Columns***

In [15]:
#Use a header variabl to keep track of the datasets
header_full = np.genfromtxt(file_location_1, delimiter = ";", encoding = "windows-1251", 
                            skip_footer= raw_data_np.shape[0], autostrip = True, dtype = np.str_)
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [16]:
#Create 2 new headers which are split based on string & numeric. These will be used later for the smaller datasets we're using.
header_strings, header_numeric= header_full[columns_strings], header_full[columns_numeric]

In [17]:
#Check the header string dataset
print(header_strings) #The names of columns containing strings

['issue_d' 'loan_status' 'term' 'grade' 'sub_grade' 'verification_status' 'url' 'addr_state']


In [18]:
#Check the header numeric dataset
print(header_numeric) #The names of columns containing numerics

['id' 'loan_amnt' 'funded_amnt' 'int_rate' 'installment' 'total_pymnt']


### **Checkpoints**
* Places throughout our code where we store a copy of our dataset (or parts of it)
* We want to avoid losing a lot of progress (if data is accidentally overwritten)
* An extremely reliable practice when we need to clean or preprocess many parts of a dataset.
* A failsafe we can rely on.

In [19]:
#Create a checkpoint function to save data before we progress further
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header= checkpoint_header, data= checkpoint_data)
    checkpoint_variable= np.load(file_name + ".npz") #Ensure, to add '.npz'
    return(checkpoint_variable)

In [20]:
#Test the checkpoint function by storing the values
checkpoint_test= checkpoint("checkpoint-test", header_strings, loan_data_strings)

In [21]:
#Now call the test checkpoint function
checkpoint_test["header"]

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [22]:
#Now call the test checkpoint function
checkpoint_test["data"]

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

In [23]:
#Now test the checkpoint function has the same data as the original
np.array_equal(checkpoint_test['data'], loan_data_strings) #Yes! Verified!

True

### **Manipulating Text Data**

#### ***Manipulating String Columns***

In [24]:
#Output the strings column header
header_strings #These columns contain text data

array(['issue_d', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [25]:
#Change name of header 1 for clarity
header_strings[0]= "issue_date"

In [26]:
#Now check base dataset
loan_data_strings

array([['May-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226', 'CA'],
       ['', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261', 'NY'],
       ['Sep-15', 'Current', '36 months', ..., 'Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', 'PA'],
       ...,
       ['Jun-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990', 'CA'],
       ['Apr-15', 'Current', '36 months', ..., 'Source Verified',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151', 'OH'],
       ['Dec-15', 'Current', '36 months', ..., '',
        'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249', 'IL']],
      dtype='<U69')

#### ***Issue Date***
* Represent month values as integers
* As integer values use less memory (storage) vis-a'-vis strings
* Using numbers, we also get a more easy to follow order of months

In [27]:
#Only display the first column of the dataset
loan_data_strings[:,0]

array(['May-15', '', 'Sep-15', ..., 'Jun-15', 'Apr-15', 'Dec-15'], dtype='<U69')

In [28]:
#Only display the first column of the dataset with unique values
np.unique(loan_data_strings[:,0]) #Empty space means missing data. The data is arranged alphabetically and not chronologically as Python doesn't recognize them as time stamps as of yet.

array(['', 'Apr-15', 'Aug-15', 'Dec-15', 'Feb-15', 'Jan-15', 'Jul-15', 'Jun-15', 'Mar-15',
       'May-15', 'Nov-15', 'Oct-15', 'Sep-15'], dtype='<U69')

In [29]:
#Strip data part to get the string data only, ie, strip excess data
loan_data_strings[:,0]= np.chararray.strip(loan_data_strings[:,0], "-15") #Strip the '-15' part

In [30]:
#Call unique function again to check if it was successful
np.unique(loan_data_strings[:,0]) #Yes! It was.

array(['', 'Apr', 'Aug', 'Dec', 'Feb', 'Jan', 'Jul', 'Jun', 'Mar', 'May', 'Nov', 'Oct', 'Sep'],
      dtype='<U69')

In [31]:
#Store the months in a new array with months proper order. Begin with empty space.
months= np.array(["", "Jan", "Feb", "Mar", "Apr", "May", "Jun",
                  "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"])

In [32]:
#Use a loop to traverse the isue date column and assign a numerical equivalent for the months
for i in range(13):
    loan_data_strings[:,0]= np.where(loan_data_strings[:,0] == months[i], #If month value matches then go to step 2.
                                     i, #Assign it this value if it matches. The index from month[i] will match the string month in loan_data_strings dataset.
                                     loan_data_strings[:,0]) #Dont change value if it doesn't match

In [33]:
#Verify if it is done
np.unique(loan_data_strings[:,0]) #Yes, it has worked correctly!

array(['0', '1', '10', '11', '12', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U69')

#### ***Loan Status***

In [34]:
#Check the header data again for the column names
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [35]:
#Display the entire loan_status column with indexing
loan_data_strings[:,1] #loan_status is at column index 1.

array(['Current', 'Current', 'Current', ..., 'Current', 'Current', 'Current'], dtype='<U69')

In [36]:
#Display the unique values of the loan_status column with indexing
np.unique(loan_data_strings[:,1]) #This makes more sense now.

array(['', 'Charged Off', 'Current', 'Default', 'Fully Paid', 'In Grace Period', 'Issued',
       'Late (16-30 days)', 'Late (31-120 days)'], dtype='<U69')

In [37]:
#Check the number of unique attributes in the column
np.unique(loan_data_strings[:,1]).size

9

In [38]:
#Check the memory size of the file (optional step)
loan_data_strings.__sizeof__() #The file occupies 22.08 Mb or 22080128 bytes of space

22080128

***Tips:**
* We can use np.where() to assign a different number to each one.
* We need to split all possible values into ether group (good v bad)
* Regressions only care if the candidates are in good financial condition
* For loans/credits always have to be risk-averse.
* Good '1' - 'Current', 'Fully Paid', 'In Grace Period', 'Issued', 'Late (16-30 days): This can be due to getting salary at a fixed date & then paying.
* Bad '0' - 'Charged Off', 'Default', ' '(No Date Provided), 'Late (31-120 days): This suggest there is a high possiblity candidate cannot keep up & default.

In [39]:
#Create an array with all the bad loan statuses
status_bad= np.array(['', 'Charged Off', 'Default', 'Late (31-120 days)'])

In [40]:
#Check if there is bad status in the loan dataset
loan_data_strings[:,1]= np.where(np.isin(loan_data_strings[:,1], status_bad), 0, 1) 
#If it is there, assign it a 0 or else a 1.

In [41]:
#Check if substitution is successful
np.unique(loan_data_strings[:,1]) #Yes! it is.

array(['0', '1'], dtype='<U69')

#### ***Term***

In [42]:
#Display the string column header
header_strings

array(['issue_date', 'loan_status', 'term', 'grade', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [43]:
#Pick the second column, ie, Term column
loan_data_strings[:,2]

array(['36 months', '36 months', '36 months', ..., '36 months', '36 months', '36 months'],
      dtype='<U69')

In [44]:
#Now look for the unique values
np.unique(loan_data_strings[:,2])

array(['', '36 months', '60 months'], dtype='<U69')

In [45]:
#Strip the excess data,i.e, 'months' string
loan_data_strings[:,2]= np.chararray.strip(loan_data_strings[:,2], " months")
loan_data_strings[:,2] #Call the function to check

array(['36', '36', '36', ..., '36', '36', '36'], dtype='<U69')

In [46]:
#Rename the term column to simplify it 
header_strings[2]= "term_months"

In [47]:
#Substitute the values that match. When we have missing date, we assume the worst in Credit/Loan cases.
loan_data_strings[:,2]= np.where(loan_data_strings[:,2] == "",
                                 "60", #As 60 months is a very long period, we use that for the worst case scenario in missing values cases.
                                 loan_data_strings[:,2])

In [48]:
#Now look for the unique values. Normally for 2 value columns we use '0' & '1'. We should ensure that other values are optimal if 0 & 1 not used.
np.unique(loan_data_strings[:,2]) #The missing value "" is gone & replaced with 60 months term.

array(['36', '60'], dtype='<U69')

#### ***Grade & Sub-Grade Data***

In [49]:
#Call the header string function to check all columns
header_strings

array(['issue_date', 'loan_status', 'term_months', 'grade', 'sub_grade', 'verification_status',
       'url', 'addr_state'], dtype='<U19')

In [50]:
#Get the unique values from the grade column to improve our understanding of the data.
np.unique(loan_data_strings[:,3])

array(['', 'A', 'B', 'C', 'D', 'E', 'F', 'G'], dtype='<U69')

In [51]:
#Get the unique values from the sub-grade column to improve our understanding of the data.
np.unique(loan_data_strings[:,4]) #Both grade & sub-grade are interdependent

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

##### ***Filling Sub-Grade***

In [52]:
#Fillout emput spaces by traversing the sub-grade array
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4]= np.where((loan_data_strings[:,4] == "") & (loan_data_strings[:,3] == i),
                                     i + '5', #The second condition is to check that the current iterator matches the current grade
                                     loan_data_strings[:,4]) #To ensure that there is no mismatch between grade & sub-grade

In [53]:
#To verify the output. We still have '',ie, we still have missing data.
np.unique(loan_data_strings[:,4]) #We still have rows where there are no grades/subgrades

array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
       'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
       'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69')

In [54]:
#To verify the output. We see that there are exactly 9 missing values from a row of 10,000 data values. 
np.unique(loan_data_strings[:,4], return_counts= True) #We can drop these 9 missing values as they are an insignificant part of the analysis. 
#However, as credit risk analysts we have to give every applicant a category

(array(['', 'A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4',
        'C5', 'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4',
        'F5', 'G1', 'G2', 'G3', 'G4', 'G5'], dtype='<U69'),
 array([  9, 285, 278, 239, 323, 592, 509, 517, 530, 553, 633, 629, 567, 586, 564, 577, 391, 267,
        250, 255, 288, 235, 162, 171, 139, 160,  94,  52,  34,  43,  24,  19,  10,   3,   7,   5],
       dtype=int64))

In [55]:
#Fillout missing value with lowest category as missing values should be penalized.
for i in np.unique(loan_data_strings[:,3])[1:]:
    loan_data_strings[:,4]= np.where((loan_data_strings[:,4] == ""),
                                     'H1', 
                                     loan_data_strings[:,4]) 

In [56]:
#Now check the dataset again
np.unique(loan_data_strings[:,4]) #We can see the new category H1. It was successful!!

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

#### ***Removing Grade***
* We remove Grade and only use sub-grade to reduce excess data and make analytics easier.

In [57]:
#We remove the grade column altogether.
loan_data_strings= np.delete(loan_data_strings, 3, axis= 1)

In [58]:
#now check if previous column 3 is removed.
loan_data_strings[:,3] #Yes, grade is deleted & replaced at column 3 by sub-grade.

array(['C3', 'A5', 'B5', ..., 'A5', 'D2', 'A4'], dtype='<U69')

In [59]:
#Ensure that the header strings file is also updated with Grade column removal.
header_strings= np.delete(header_strings, 3)

In [60]:
#Now check the 4th column of the header string dataset
header_strings[3]

'sub_grade'

#### ***Converting Sub-Grade***

In [61]:
#Display the unique sub-grade column values again for perusal
np.unique(loan_data_strings[:,3]) #Many different values that we can convert into numerics

array(['A1', 'A2', 'A3', 'A4', 'A5', 'B1', 'B2', 'B3', 'B4', 'B5', 'C1', 'C2', 'C3', 'C4', 'C5',
       'D1', 'D2', 'D3', 'D4', 'D5', 'E1', 'E2', 'E3', 'E4', 'E5', 'F1', 'F2', 'F3', 'F4', 'F5',
       'G1', 'G2', 'G3', 'G4', 'G5', 'H1'], dtype='<U69')

In [62]:
#Now construct a dictionary to convert the values into numeric. The + 1 at the end is necesary as range is close to open and it means the last number isn't included ie, only 35 values. So, +1 is needed for 36 values.
keys= list(np.unique(loan_data_strings[:,3])) #Every key is a sub-grade as a string 
values= list(range(1, np.unique(loan_data_strings[:,3]).shape[0] + 1)) #Numeric values for each subgrade ranging from 1 - 35 + 1,ie, 1 - 36 values. (As range doesn't contain last value) 
dict_sub_grade= dict(zip(keys, values)) #Create a new dictionary with these values, with values acting as ranks of trustworthiness.

In [63]:
#Now check the results
dict_sub_grade

{'A1': 1,
 'A2': 2,
 'A3': 3,
 'A4': 4,
 'A5': 5,
 'B1': 6,
 'B2': 7,
 'B3': 8,
 'B4': 9,
 'B5': 10,
 'C1': 11,
 'C2': 12,
 'C3': 13,
 'C4': 14,
 'C5': 15,
 'D1': 16,
 'D2': 17,
 'D3': 18,
 'D4': 19,
 'D5': 20,
 'E1': 21,
 'E2': 22,
 'E3': 23,
 'E4': 24,
 'E5': 25,
 'F1': 26,
 'F2': 27,
 'F3': 28,
 'F4': 29,
 'F5': 30,
 'G1': 31,
 'G2': 32,
 'G3': 33,
 'G4': 34,
 'G5': 35,
 'H1': 36}

In [64]:
#Pass the numeric value for the grades
for i in np.unique(loan_data_strings[:,3]): #For Loop goes through the unique array
    loan_data_strings[:,3]= np.where(loan_data_strings[:,3] == i, #Condition to match this value
                                     dict_sub_grade[i], #If matched, pass the associated value
                                     loan_data_strings[:,3])

In [65]:
#Call the unique function to check the values
np.unique(loan_data_strings[:,3]) #We see many numbers saved as strings. Verified!! 

array(['1', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19', '2', '20', '21', '22',
       '23', '24', '25', '26', '27', '28', '29', '3', '30', '31', '32', '33', '34', '35', '36',
       '4', '5', '6', '7', '8', '9'], dtype='<U69')

#### ***Verification Status***

In [66]:
#Call the header strings function to check the data
header_strings #As previous grade column was deleted, column index 4 is now verification status

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [67]:
#Check the unique values of the dataset
np.unique(loan_data_strings[:,4])

array(['', 'Not Verified', 'Source Verified', 'Verified'], dtype='<U69')

In [68]:
#Assume empty space "" is equivalent to not verified as per policy.
loan_data_strings[:,4]= np.where((loan_data_strings[:,4] == '') | (loan_data_strings[:,4] == 'Not Verified'), #Check if conditions match
                                 0, #Assign '0' if the condition is met
                                 1) #Assign '1' otherwise

In [69]:
#Not verify if the conversion was successful
np.unique(loan_data_strings[:,4])

array(['0', '1'], dtype='<U69')

#### ***URL***

In [70]:
#Call the header-string function to check column integrity
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status', 'url',
       'addr_state'], dtype='<U19')

In [71]:
#Get the url column from the dataset
loan_data_strings[:,5]

array(['https://www.lendingclub.com/browse/loanDetail.action?loan_id=48010226',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=57693261',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=59432726', ...,
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=50415990',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=46154151',
       'https://www.lendingclub.com/browse/loanDetail.action?loan_id=66055249'], dtype='<U69')

In [72]:
#Strip the excess data & only keep the numeric part. As we are not losing any crucial data, it is safe to overwrite this column.
np.chararray.strip(loan_data_strings[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")

chararray(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'],
          dtype='<U69')

In [73]:
#As we are not losing any crucial data, it is safe to overwrite this column.
loan_data_strings[:,5]= np.chararray.strip(loan_data_strings[:,5], "https://www.lendingclub.com/browse/loanDetail.action?loan_id=")
loan_data_strings[:,5]

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [74]:
#Call the header full function to check all the headers
header_full

array(['id', 'issue_d', 'loan_amnt', 'loan_status', 'funded_amnt', 'term', 'int_rate',
       'installment', 'grade', 'sub_grade', 'verification_status', 'url', 'addr_state',
       'total_pymnt'], dtype='<U19')

In [75]:
#Check the numeric loan_data for comparision
loan_data_numeric[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [76]:
#Now check the string loan_data to compare with above
loan_data_strings[:,5] #Both are same values but different data types.

array(['48010226', '57693261', '59432726', ..., '50415990', '46154151', '66055249'], dtype='<U69')

In [77]:
#Verify both dataset values are the same
np.array_equal(loan_data_numeric[:,0].astype(dtype=np.int32), 
               loan_data_strings[:,5].astype(dtype=np.int32)) #Yes, both values are identical.

True

In [78]:
#Remove url from header and from strings loan data to clean it.
loan_data_strings= np.delete(loan_data_strings, 5, axis= 1)
header_strings= np.delete(header_strings, 5)

In [79]:
#Call the datasets to verify
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [80]:
#Call the header strings dataset to verify
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [81]:
#Check to verify that we did not delete irretrievable information
loan_data_numeric[:,0] #Data is still there!

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [82]:
#Verify that the correct column data is also intact
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ***State Address***

In [83]:
#Check all the colmuns of header strings
header_strings

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'addr_state'], dtype='<U19')

In [84]:
#Rename the column to a better one
header_strings[5]= 'state_address'

In [85]:
#Check the column data
loan_data_strings[:,5]

array(['CA', 'NY', 'PA', ..., 'CA', 'OH', 'IL'], dtype='<U69')

In [86]:
#Now get the unique values to make sense of the dataset values. Baseline benchmark: Iowa.
np.unique(loan_data_strings[:,5]) #US States along with missing value ''. Iowa is the missing state as a baseline benchmark.

array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
       'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
       'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
       'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69')

*Tips:
* When doing research or analysis on a variable with many categories, it is normal to pick one as a benchmark and include dummy variables for the rest. 
* The one without the dummy variable will serve as the base case.
* We can increase/decrease the rest based in their coefficients.

In [87]:
#Get the unique value size of the column
np.unique(loan_data_strings[:,5]).size

50

In [88]:
#Now get the unique values to make sense of the dataset values. 
np.unique(loan_data_strings[:,5], return_counts= True) #Values are sorted in alphabetical order instead of numerical (population) values.

(array(['', 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DC', 'DE', 'FL', 'GA', 'HI', 'IL', 'IN',
        'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI', 'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH',
        'NJ', 'NM', 'NV', 'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 'VA',
        'VT', 'WA', 'WI', 'WV', 'WY'], dtype='<U69'),
 array([ 500,   26,  119,   74,  220, 1336,  201,  143,   27,   27,  690,  321,   44,  389,  152,
          84,   84,  116,  210,  222,   10,  267,  156,  160,   61,   28,  261,   16,   25,   58,
         341,   57,  130,  777,  312,   83,  108,  320,   40,  107,   24,  143,  758,   74,  242,
          17,  216,  148,   49,   27], dtype=int64))

In [89]:
#Sort the dataset according to number of applicants to make sense of the data.
#Use tuple assignment to store new variables
states_names, states_count= np.unique(loan_data_strings[:,5], return_counts= True)
states_count_sorted= np.argsort(-states_count) #-ve sign to sort it via descending order
states_names[states_count_sorted], states_count[states_count_sorted] #Display variables according to the sorted indices.
#There are more counts of missing values than 45 other US states.

(array(['CA', 'NY', 'TX', 'FL', '', 'IL', 'NJ', 'GA', 'PA', 'OH', 'MI', 'NC', 'VA', 'MD', 'AZ',
        'WA', 'MA', 'CO', 'MO', 'MN', 'IN', 'WI', 'CT', 'TN', 'NV', 'AL', 'LA', 'OR', 'SC', 'KY',
        'KS', 'OK', 'UT', 'AR', 'MS', 'NH', 'NM', 'WV', 'HI', 'RI', 'MT', 'DE', 'DC', 'WY', 'AK',
        'NE', 'SD', 'VT', 'ND', 'ME'], dtype='<U69'),
 array([1336,  777,  758,  690,  500,  389,  341,  321,  320,  312,  267,  261,  242,  222,  220,
         216,  210,  201,  160,  156,  152,  148,  143,  143,  130,  119,  116,  108,  107,   84,
          84,   83,   74,   74,   61,   58,   57,   49,   44,   40,   28,   27,   27,   27,   26,
          25,   24,   17,   16,   10], dtype=int64))

*Tips:
* We have very little data for too many states to examine each one individually.
* The more categories a variable has, the fewer data will be available for each one.
* If we assign a unique value to each state this will allow outliers to have a big influence on the coefficients. 

In [90]:
#Take care of missing values in the dataset first.
loan_data_strings[:,5]= np.where(loan_data_strings[:,5] == '',
                                 0, #Pass values of 0 so that it won't be included in any region
                                 loan_data_strings[:,5]) #If it matches then value isn't altered. 

In [91]:
#Group the states to common values to ensure more value weightage/coefficients
states_east= np.array(['PA','NY','NJ','CT','MA','VT','NH','ME','RI'])
states_west= np.array(['WA','OR','CA','NV','ID','MT','WY','UT','CO','AZ','NM','HI','AK'])
states_south= np.array(['TX','OK','AR','LA','MS','AL','TN','KY','FL','GA','SC','NC','VA','WV','MD','DE','DC'])
states_midwest= np.array(['ND','SD','NE','KS','MN','IA','MO','WI','IL','IN','MI','OH'])

https://www2.census.gov/geo/pdfs/maps-data/maps/reference/us_regdiv.pdf 

In [92]:
#Assign the variables into larger groups for easier categorization
loan_data_strings[:,5]= np.where(np.isin(loan_data_strings[:,5], states_west), 1, loan_data_strings[:,5])
loan_data_strings[:,5]= np.where(np.isin(loan_data_strings[:,5], states_south), 2, loan_data_strings[:,5])
loan_data_strings[:,5]= np.where(np.isin(loan_data_strings[:,5], states_midwest), 3, loan_data_strings[:,5])
loan_data_strings[:,5]= np.where(np.isin(loan_data_strings[:,5], states_east), 4, loan_data_strings[:,5])

In [93]:
#Verify if successful
np.unique(loan_data_strings[:,5]) #Yes verified. Values saved from 0 - 4, for easier analytical work.

array(['0', '1', '2', '3', '4'], dtype='<U69')

#### ***Converting to Numbers***

In [94]:
#Display the String dataset 
loan_data_strings #We can see it is full of numbers saved as text

array([['5', '1', '36', '13', '1', '1'],
       ['0', '1', '36', '5', '1', '4'],
       ['9', '1', '36', '10', '1', '4'],
       ...,
       ['6', '1', '36', '5', '1', '1'],
       ['4', '1', '36', '17', '1', '3'],
       ['12', '1', '36', '4', '0', '3']], dtype='<U69')

In [95]:
#Change data type from text to numeric for the dataset and store it
loan_data_strings= loan_data_strings.astype(np.int32)
loan_data_strings #Yes, successfully converted to integer/numerical datatype. 

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

#### **Checkpoint 1: Strings**

In [96]:
"""This is the checkpoint function from before
def checkpoint(file_name, checkpoint_header, checkpoint_data):
    np.savez(file_name, header= checkpoint_header, data= checkpoint_data)
    checkpoint_variable= np.load(file_name + ".npz") #Ensure, to add '.npz'
    return(checkpoint_variable)"""

'This is the checkpoint function from before\ndef checkpoint(file_name, checkpoint_header, checkpoint_data):\n    np.savez(file_name, header= checkpoint_header, data= checkpoint_data)\n    checkpoint_variable= np.load(file_name + ".npz") #Ensure, to add \'.npz\'\n    return(checkpoint_variable)'

In [97]:
#Create a new checkpoint for the String data so far & also save it in a new varaiable
checkpoint1="Checkpoint-Strings" #Output in same folder
checkpoint_strings= checkpoint(checkpoint1, header_strings, loan_data_strings)

In [98]:
#Call the checkpoint variable with header argument
checkpoint_strings["header"]

array(['issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

In [99]:
#Call the checkpoint variable with data argument
checkpoint_strings["data"]

array([[ 5,  1, 36, 13,  1,  1],
       [ 0,  1, 36,  5,  1,  4],
       [ 9,  1, 36, 10,  1,  4],
       ...,
       [ 6,  1, 36,  5,  1,  1],
       [ 4,  1, 36, 17,  1,  3],
       [12,  1, 36,  4,  0,  3]])

In [100]:
#To be absolutely certain the 2 datasets are a match
np.array_equal(checkpoint_strings['data'], loan_data_strings) #Only use the data argument as check_point strings also contains the header data.

True

### **Manipulating Numeric Data**

In [101]:
#Display the Numeric loan data to gain insights
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  , 68616520.  ,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  , 68616520.  ,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  , 68616520.  , 68616520.  ,     2185.64],
       [46154151.  , 68616520.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  , 68616520.  ,      309.97,      301.9 ]])

In [102]:
#Check for missing values in the dataset and how many there are. 
np.isnan(loan_data_numeric).sum() #No missing values!

0

#### ***Substitute Filler Values***
* There aren't any missing values because we used filler values instead.
* Therefore, we must substitute those filler values with the worst possible values.

In [103]:
#Check the header data to see all the columns it contains
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ***ID***
* To check whether any of the elements of the column equal the temporary_fill values

In [104]:
#Reminder of the temporary fill value
temporary_fill

68616520.0

In [105]:
#Now check the 1st column
np.isin(loan_data_numeric[:,0], temporary_fill)

array([False, False, False, ..., False, False, False])

In [106]:
#Now use the sum method to get the actual results
np.isin(loan_data_numeric[:,0], temporary_fill).sum() #Column 1 doesn't contain filler values.

0

In [107]:
#Check the header columns again to identify the minimum value
header_numeric #Only funded-amt could have the minimum amount considered the worst.
#Thus we will switch the minimum value of funded_amt & the maximum value of all the other columns.

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

#### ***Temporary Stats***

In [108]:
#We had stored the min, mean & max in the temporary stats variable. Display to check content.
temporary_stats

array([[  373332.  ,         nan,     1000.  ,         nan,     1000.  ,         nan,        6.  ,
              31.42,         nan,         nan,         nan,         nan,         nan,        0.  ],
       [54015809.19,         nan,    15273.46,         nan,    15311.04,         nan,       16.62,
             440.92,         nan,         nan,         nan,         nan,         nan,     3143.85],
       [68616519.  ,         nan,    35000.  ,         nan,    35000.  ,         nan,       28.99,
            1372.97,         nan,         nan,         nan,         nan,         nan,    41913.62]])

In [109]:
"""#Use indexing & plugin columns to ignore the NAN (string) values 
temporary_stats[:, header_numeric] #IndexError: arrays used as indices must be of integer (or boolean) type"""

'#Use indexing & plugin columns to ignore the NAN (string) values \ntemporary_stats[:, header_numeric] #IndexError: arrays used as indices must be of integer (or boolean) type'

In [110]:
#Use indexing & plugin columns to ignore the NAN (string) values 
temporary_stats[:, columns_numeric] #Temporary Min, Mean & Max respectively by rows.

array([[  373332.  ,     1000.  ,     1000.  ,        6.  ,       31.42,        0.  ],
       [54015809.19,    15273.46,    15311.04,       16.62,      440.92,     3143.85],
       [68616519.  ,    35000.  ,    35000.  ,       28.99,     1372.97,    41913.62]])

#### ***Funded Amount***

In [111]:
#Check the 3rd column for insights
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [112]:
#Funded amount should be substituted with minimum amount as that would make the most sense in context of credit/loan applications
#Why? - Because we cannot expect max funded amount if the values are missing
#Always be risk averse in credit/loan applications
loan_data_numeric[:,2]= np.where(loan_data_numeric[:,2] == temporary_fill,
                                 temporary_stats[0, columns_numeric[2]],
                                 loan_data_numeric[:,2])
loan_data_numeric[:,2]

array([35000., 30000., 15000., ..., 10000., 10000., 10000.])

In [113]:
#Display the 4th individual element of the temporary stats variable
temporary_stats[0,3] #This is because we generated temporary stats even before converting the loan-status string data to numeric.

nan

In [114]:
#Display the 4th numeric column from temporary stats
temporary_stats[0, columns_numeric[3]]

6.0

#### ***Loaned Amount, Interest Rate, Total Payment, Installation***

In [115]:
#Display the numeric header again to check columns 
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt'], dtype='<U19')

In [116]:
#Now iterate the column data of all columns except column 2 with the max value 
for i in [1,3,4,5]:
    loan_data_numeric[:,i]= np.where(loan_data_numeric[:,i] == temporary_fill,
                                     temporary_stats[2, columns_numeric[i]], # Row 2 in temporary_stats contains the max value of the columns
                                     loan_data_numeric[:,i])

In [117]:
#Now check the altered dataset with the filler values changed to max values in columns 1,3,4,5 & min values in column 2.
loan_data_numeric #The filler values are now substituted with more fitting alternatives.

array([[48010226.  ,    35000.  ,    35000.  ,       13.33,     1184.86,     9452.96],
       [57693261.  ,    30000.  ,    30000.  ,       28.99,      938.57,     4679.7 ],
       [59432726.  ,    15000.  ,    15000.  ,       28.99,      494.86,     1969.83],
       ...,
       [50415990.  ,    10000.  ,    10000.  ,       28.99,     1372.97,     2185.64],
       [46154151.  ,    35000.  ,    10000.  ,       16.55,      354.3 ,     3199.4 ],
       [66055249.  ,    10000.  ,    10000.  ,       28.99,      309.97,      301.9 ]])

### ***Currency Change***

#### ***The Exchange Rate***
* To ensure that the currency data can be easily converted to another for analytics at the "time of the credit/loan application".
* We will need to convert the default currency from USD to EUR (based on office location & Data Analytics requirements for this project).

In [118]:
#Gather the EURO to Dollar Historical Exchange Rate File and pull the data. We will use it for exchange rates function.
file_location_2= "EUR-USD.csv"
EUR_USD= np.genfromtxt(file_location_2, delimiter= ",", autostrip= True)
EUR_USD

array([[ nan,  nan,  nan,  nan,  nan],
       [1.21, 1.21, 1.11, 1.13, 0.  ],
       [1.13, 1.15, 1.12, 1.12, 0.  ],
       [1.12, 1.12, 1.05, 1.08, 0.  ],
       [1.07, 1.12, 1.05, 1.11, 0.  ],
       [1.12, 1.15, 1.08, 1.1 , 0.  ],
       [1.1 , 1.14, 1.09, 1.12, 0.  ],
       [1.11, 1.12, 1.08, 1.09, 0.  ],
       [1.1 , 1.17, 1.09, 1.13, 0.  ],
       [1.12, 1.15, 1.11, 1.13, 0.  ],
       [1.12, 1.15, 1.09, 1.1 , 0.  ],
       [1.1 , 1.11, 1.06, 1.06, 0.  ],
       [1.06, 1.11, 1.05, 1.09, 0.  ]])

In [119]:
#Change dtype to strings to check the column names 
EUR_USD= np.genfromtxt(file_location_2, delimiter= ",", autostrip= True, dtype= np.str_)
EUR_USD #Okay now we see the columns as Open, High, Low, Close & Volume. Data about stock prices & exchange rates.
#Open: Exchange rate at beginning of day, High: Highest value of the day, Low: Lowest value of the day,
#Close: Exchange rate at end of day,ie, Adjusted closing prices, Volume: The number of trades made on that day
#However, volume is 0, as exchange rate doesn't buy/sell itself.

array([['Open', 'High', 'Low', 'Close', 'Volume'],
       ['1.2098628282546997', '1.2098628282546997', '1.11055588722229', '1.1287955045700073', '0'],
       ['1.1287955045700073', '1.1484194993972778', '1.117680549621582', '1.1205360889434814',
        '0'],
       ['1.119795799255371', '1.1240400075912476', '1.0460032224655151', '1.0830246210098267',
        '0'],
       ['1.0741022825241089', '1.1247594356536865', '1.0521597862243652', '1.1114321947097778',
        '0'],
       ['1.1215037107467651', '1.145304799079895', '1.0821995735168457', '1.0960345268249512',
        '0'],
       ['1.095902442932129', '1.1428401470184326', '1.0888904333114624', '1.122296690940857', '0'],
       ['1.1134989261627197', '1.1219995021820068', '1.081270456314087', '1.0939244031906128',
        '0'],
       ['1.0969001054763794', '1.1705996990203857', '1.0850305557250977', '1.1340054273605347',
        '0'],
       ['1.1225990056991577', '1.1460003852844238', '1.1089695692062378', '1.1255937814712524

In [120]:
#Only get the 'Close' column from the file for analytics..
#As we only care about the adjusted closing prices for our analytics here, we only need to use that.
EUR_USD= np.genfromtxt(file_location_2, delimiter= ",", autostrip= True, 
                       skip_header= 1, usecols= 3)
EUR_USD #We only require exchange rates at the close of the day for our analytics. Hence, high, low, open & volume can be safely ignored.

array([1.13, 1.12, 1.08, 1.11, 1.1 , 1.12, 1.09, 1.13, 1.13, 1.1 , 1.06, 1.09])

In [121]:
#Check all the issue dates from Loan Data Strings dataset
loan_data_strings[:,0] #The value represents which month it was issued. 

array([ 5,  0,  9, ...,  6,  4, 12])

In [122]:
#As we are not using a fixed exchange rate, we have to make adjustments and store it for each account.
exchange_rate= loan_data_strings[:,0] #Because it contains all the application issue dates

for i in range(1,13): #Goes through 1 - 12 months 
    exchange_rate = np.where(exchange_rate == i,
                             EUR_USD[i-1], #Substitute for average exchange rate. i-1 is used here, 
                             exchange_rate) #as index in starts from 0: Jan.

#For accounts with no issue dates: Assign the annual exchange rate for 2015 (reasonable assumption)
exchange_rate = np.where(exchange_rate == 0,
                         np.mean(EUR_USD),
                         exchange_rate)

#Now display the new variable
exchange_rate #Contains the associated exchange rate for every element of the dataset.

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [123]:
#Check all the unique values of the dataset
np.unique(exchange_rate) #Minimum: 0, Maximum: 1.13

array([1.06, 1.08, 1.09, 1.09, 1.1 , 1.1 , 1.11, 1.11, 1.12, 1.12, 1.13, 1.13, 1.13])

In [124]:
#Check if the shape attributes are comparable
exchange_rate.shape #1-D Array

(10000,)

In [125]:
#Check if the shape attributes are comparable
loan_data_numeric.shape #2-D Array

(10000, 6)

In [126]:
#Now we need to rehape exchange rate so that we can add the data to the loan data numeric dataset
exchange_rate= np.reshape(exchange_rate, (10000,1))

In [127]:
#Now use hstack function to add the exchange rate data to loan data numeric dataset
loan_data_numeric= np.hstack((loan_data_numeric, exchange_rate)) #Save it in the dataset

In [128]:
#Display the newly amended dataset
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,     1184.86,     9452.96,        1.1 ],
       [57693261.  ,    30000.  ,    30000.  , ...,      938.57,     4679.7 ,        1.11],
       [59432726.  ,    15000.  ,    15000.  , ...,      494.86,     1969.83,        1.13],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     1372.97,     2185.64,        1.12],
       [46154151.  ,    35000.  ,    10000.  , ...,      354.3 ,     3199.4 ,        1.11],
       [66055249.  ,    10000.  ,    10000.  , ...,      309.97,      301.9 ,        1.09]])

In [129]:
'''#Also, change the header numeric function as a new column has been added
header_numeric= np.concatenate((header_numeric, 'exchange_rate')) #1-D vectore & 0-D scalar. Hence, error.
header_numeric #ValueError: all the input arrays must have same number of dimensions, 
#but the array at index 0 has 1 dimension(s) and the array at index 1 has 0 dimension(s)'''

"#Also, change the header numeric function as a new column has been added\nheader_numeric= np.concatenate((header_numeric, 'exchange_rate')) #1-D vectore & 0-D scalar. Hence, error.\nheader_numeric #ValueError: all the input arrays must have same number of dimensions, \n#but the array at index 0 has 1 dimension(s) and the array at index 1 has 0 dimension(s)"

In [130]:
#Also, change the header numeric function as a new column has been added
header_numeric= np.concatenate((header_numeric, np.array(['exchange_rate']))) 
header_numeric #Converted 0-D scalar to array to solve the error. Success!!

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

#### ***Currency Change***
##### ***From USD to EUR***

In [131]:
#Have another look at the header to verify
header_numeric #We can see 4 columns, loan & funded amount, installment & total payment,
#to be in dollars 

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate'],
      dtype='<U19')

In [132]:
#To avoid repetitive code for currency conversion, we use a new variable
columns_dollar= np.array([1,2,4,5]) #All the columns using dollars by default

In [133]:
#Now display only the dollar columns in a 2-D array.
loan_data_numeric[:,[columns_dollar]]

array([[[35000.  , 35000.  ,  1184.86,  9452.96]],

       [[30000.  , 30000.  ,   938.57,  4679.7 ]],

       [[15000.  , 15000.  ,   494.86,  1969.83]],

       ...,

       [[10000.  , 10000.  ,  1372.97,  2185.64]],

       [[35000.  , 10000.  ,   354.3 ,  3199.4 ]],

       [[10000.  , 10000.  ,   309.97,   301.9 ]]])

In [134]:
#Now display the exchange rate column only
loan_data_numeric[:,6]

array([1.1 , 1.11, 1.13, ..., 1.12, 1.11, 1.09])

In [135]:
#Add the euro version of the data to the dollar counterpart
#To do that we will run a loop replacing the dollar data and stack it horizontally 
for i in columns_dollar:
    loan_data_numeric = np.hstack((loan_data_numeric, 
                                   np.reshape(loan_data_numeric[:,i] / loan_data_numeric[:,6], 
                                              (10000,1))))

#The loan data numeric equals the horizontal stacking hstack. The first input will be the entire datasaet loan_data_numeric,
#because we want the existing dataset. Then we'll reference a column depending on the iterator variable i, and then divide it by the exchange rate (stored in 7th column of the numeric dataset).
#We need to divide by exchange rate as it shows how much the euro is worth in dollars, rather than multiply it to get the corresponding numbers in euros.

In [136]:
#Now check the new dataset
loan_data_numeric #Had to use loan_data_numeric[:, i] / 1.10 to ensure data integrity instead,
#of having values divided by 0 & skewing data. 

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [137]:
#Now check the new dataset shape
loan_data_numeric.shape

(10000, 11)

#### ***Expanding the Header***

In [138]:
#Also need to update the header as new columns were added to the dataset
header_additional= np.array([column_name + '_EUR' 
                             for column_name 
                             in header_numeric[columns_dollar]]) 
#Goes through the dollar columns and attaching _EUR after each one

In [139]:
#Now check the additional header 
header_additional

array(['loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U15')

In [140]:
#Add this new header to the old header numeric 
header_numeric= np.concatenate((header_numeric, header_additional))
header_numeric

array(['id', 'loan_amnt', 'funded_amnt', 'int_rate', 'installment', 'total_pymnt', 'exchange_rate',
       'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'], dtype='<U19')

In [141]:
#Good practise to also change the dollar header columns to USD
header_numeric[columns_dollar]= np.array([column_name + '_USD' 
                                          for column_name 
                                          in header_numeric[columns_dollar]]) 
#Goes through the dollar columns and attaching _USD after each one

In [142]:
#Now check the updated numeric header data
header_numeric

array(['id', 'loan_amnt_USD', 'funded_amnt_USD', 'int_rate', 'installment_USD', 'total_pymnt_USD',
       'exchange_rate', 'loan_amnt_EUR', 'funded_amnt_EUR', 'installment_EUR', 'total_pymnt_EUR'],
      dtype='<U19')

In [143]:
#Now create a list and we rearrange the columns so that the corresponding USD & EUR columns are adjacent for data clarity
columns_index_order= [0,1,7,2,8,3,4,9,5,10,6] #USD-EUR side-by-side for clarity

In [144]:
#Now call numeric header and rearrange index using the above list
header_numeric= header_numeric[columns_index_order] #Columns rearranged neatly for data clarity
header_numeric #The dollar columns precede their euro equivalents

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [145]:
#Call numeric loan dataset to check its data
loan_data_numeric

array([[48010226.  ,    35000.  ,    35000.  , ...,    31933.3 ,     1081.04,     8624.69],
       [57693261.  ,    30000.  ,    30000.  , ...,    27132.46,      848.86,     4232.39],
       [59432726.  ,    15000.  ,    15000.  , ...,    13326.3 ,      439.64,     1750.04],
       ...,
       [50415990.  ,    10000.  ,    10000.  , ...,     8910.3 ,     1223.36,     1947.47],
       [46154151.  ,    35000.  ,    10000.  , ...,     8997.4 ,      318.78,     2878.63],
       [66055249.  ,    10000.  ,    10000.  , ...,     9145.8 ,      283.49,      276.11]])

In [146]:
#Arrange the numeric dataset according to the new index order
loan_data_numeric= loan_data_numeric[:,columns_index_order]
loan_data_numeric

array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
       [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
       [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
       [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
       [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]])

***Tips:**
* We appropriately filled out any missing values
* Added exchange rates for each applicants (account)
* Created EUR versions of the 4 monetary values

#### ***Interest Rate***
* Assumption: Doesn't change according to currency.

In [147]:
#Disaply the numeric header
header_numeric

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
      dtype='<U19')

In [148]:
#Now check the numeric loan dataset 
loan_data_numeric[:,5]

array([13.33, 28.99, 28.99, ..., 28.99, 16.55, 28.99])

In [149]:
#Check the columns unique values
np.unique(loan_data_numeric[:,5]) #Min Interest: 6.00%, Maximum Interest: 28.99%

array([ 6.  , 13.18, 13.33, 13.44, 13.66, 13.67, 13.99, 14.31, 14.33, 14.48, 14.65, 14.85, 14.99,
       15.41, 15.59, 15.61, 15.77, 15.99, 16.49, 16.55, 16.59, 16.99, 17.14, 17.27, 17.57, 17.86,
       17.97, 18.25, 18.49, 18.54, 18.55, 18.84, 18.99, 19.19, 19.24, 19.48, 19.52, 19.89, 19.99,
       20.49, 20.99, 21.67, 21.99, 22.99, 23.99, 24.24, 24.99, 25.57, 25.78, 25.83, 25.89, 25.99,
       26.77, 26.99, 27.31, 27.49, 27.88, 28.49, 28.99])

In [150]:
#Transform the interest rate column to float value instead of percentages
loan_data_numeric[:,5]= loan_data_numeric[:,5]/100 #Now all values converted to float
loan_data_numeric[:,5] #Success! Now this will make analytics easier! 

array([0.13, 0.29, 0.29, ..., 0.29, 0.17, 0.29])

### **Checkpoint 2: Numeric**

In [151]:
#Call the checkpoint function now for the numeric dataset
checkpoint2="Checkpoint-Numeric" #Output in same folder
checkpoint_numeric= checkpoint(checkpoint2, header_numeric, loan_data_numeric)

In [152]:
#Now call the checkpoint variable to verify
checkpoint_numeric['header'], checkpoint_numeric['data'] #It is successful! 

(array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
        'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate'],
       dtype='<U19'),
 array([[48010226.  ,    35000.  ,    31933.3 , ...,     9452.96,     8624.69,        1.1 ],
        [57693261.  ,    30000.  ,    27132.46, ...,     4679.7 ,     4232.39,        1.11],
        [59432726.  ,    15000.  ,    13326.3 , ...,     1969.83,     1750.04,        1.13],
        ...,
        [50415990.  ,    10000.  ,     8910.3 , ...,     2185.64,     1947.47,        1.12],
        [46154151.  ,    35000.  ,    31490.9 , ...,     3199.4 ,     2878.63,        1.11],
        [66055249.  ,    10000.  ,     9145.8 , ...,      301.9 ,      276.11,        1.09]]))

### **Creating the "Complete" Dataset**
* The story so far: The original array was split up into semi-array each with string and numeric parts divided.
* Both the array were cleaned and pre-processed separately.
* Now we can finalize the dataset by combining the two. 

In [153]:
#The two arrays must have compatible shapes to be joined together
#loan_data_numeric.shape - This is also correct
#loan_data_strings.shape - This is also correct

#However, we must use checkpoints to compare as the arrays might be altered from original
checkpoint_strings['data'].shape #10000 x 6 - 2-D array

(10000, 6)

In [154]:
#Use checkpoints to compare as the arrays might be altered from original
checkpoint_numeric['data'].shape #10000 x 11 - 2-D array
#Yes, both arrays can be stacked as they have same number of rows

(10000, 11)

In [155]:
#The arrays can be stacked as they have same number of rows
#The numerical dataset will be called first as it has the ID column in it.
np.hstack((checkpoint_numeric['data'], checkpoint_strings['data'])) #Fantastic! It worked!

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [156]:
#Now check shape to see if it worked correctly. Yes, 11 + 6 columns = 17 columns.
np.hstack((checkpoint_numeric['data'], checkpoint_strings['data'])).shape

(10000, 17)

In [157]:
#Now store the stacked data in a new completed loan dataset
loan_data= np.hstack((checkpoint_numeric['data'], checkpoint_strings['data']))

In [158]:
#Now to check if it contains the stacked array
loan_data #Wonderful! It worked!! 

array([[48010226.  ,    35000.  ,    31933.3 , ...,       13.  ,        1.  ,        1.  ],
       [57693261.  ,    30000.  ,    27132.46, ...,        5.  ,        1.  ,        4.  ],
       [59432726.  ,    15000.  ,    13326.3 , ...,       10.  ,        1.  ,        4.  ],
       ...,
       [50415990.  ,    10000.  ,     8910.3 , ...,        5.  ,        1.  ,        1.  ],
       [46154151.  ,    35000.  ,    31490.9 , ...,       17.  ,        1.  ,        3.  ],
       [66055249.  ,    10000.  ,     9145.8 , ...,        4.  ,        0.  ,        3.  ]])

In [159]:
#Determine how many missing values are still left in the array. It should be 0 as the datasets were cleaned beforehand.
np.isnan(loan_data).sum() #Yes! It worked as expected!

0

In [160]:
#Now to combine the header arrays of the numeric and string header and complete it in header_full array.
header_full= np.concatenate((checkpoint_numeric['header'], checkpoint_strings['header']))
#As numeric loan dataset was stiched first, the numeric should also be first argument 
header_full

array(['id', 'loan_amnt_USD', 'loan_amnt_EUR', 'funded_amnt_USD', 'funded_amnt_EUR', 'int_rate',
       'installment_USD', 'installment_EUR', 'total_pymnt_USD', 'total_pymnt_EUR', 'exchange_rate',
       'issue_date', 'loan_status', 'term_months', 'sub_grade', 'verification_status',
       'state_address'], dtype='<U19')

#### ***Sorting the New Dataset***
* We want to rearrange the entire dataset according to the values of the first column, ie, ID column.

In [161]:
#Check the value of the first column
loan_data[:,0]

array([48010226., 57693261., 59432726., ..., 50415990., 46154151., 66055249.])

In [162]:
#Now sort the value of the first column only to check
np.sort(loan_data[:,0])

array([  373332.,   575239.,   707689., ..., 68614880., 68615915., 68616519.])

In [163]:
#Now sort the indices of the first column
np.argsort(loan_data[:,0])

array([2086, 4812, 2353, ..., 4935, 9388, 8415], dtype=int64)

In [164]:
#Now pass the dataset index with the argsort function and store the values
loan_data= loan_data[np.argsort(loan_data[:,0])] #Passed the first column as sorted index

In [165]:
#Examine the sorted dataset
loan_data

array([[  373332.  ,     9950.  ,     9038.08, ...,       21.  ,        0.  ,        1.  ],
       [  575239.  ,    12000.  ,    10900.2 , ...,       25.  ,        1.  ,        2.  ],
       [  707689.  ,    10000.  ,     8924.3 , ...,       13.  ,        1.  ,        0.  ],
       ...,
       [68614880.  ,     5600.  ,     5121.65, ...,        8.  ,        1.  ,        1.  ],
       [68615915.  ,     4000.  ,     3658.32, ...,       10.  ,        1.  ,        2.  ],
       [68616519.  ,    21600.  ,    19754.93, ...,        3.  ,        0.  ,        2.  ]])

In [166]:
#Now call argsort function on the first column again to check
np.argsort(loan_data[:,0]) #Yes, Verified!

array([   0,    1,    2, ..., 9997, 9998, 9999], dtype=int64)

#### ***Storing the New Dataset***
* Now we can stack the header dataset alongwith the combined loan dataset to complete it. 

In [167]:
#Stack the header vertically with the dataset. dtype converted to Unicode-32.
np.vstack((header_full, loan_data)) #Header argument first to ensure, header stays on top
#We see that the stack converted all the data to text again.
#This is because the stack requires a unified datatype across all rows & columns
#By default, the function selects the smallest datatype that can hold any of the elements within the array

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [168]:
#Now store the values in the combined array dataset
loan_data= np.vstack((header_full, loan_data)) 
loan_data #It worked!!!

array([['id', 'loan_amnt_USD', 'loan_amnt_EUR', ..., 'sub_grade', 'verification_status',
        'state_address'],
       ['373332.0', '9950.0', '9038.082814338286', ..., '21.0', '0.0', '1.0'],
       ['575239.0', '12000.0', '10900.20037910145', ..., '25.0', '1.0', '2.0'],
       ...,
       ['68614880.0', '5600.0', '5121.647851612413', ..., '8.0', '1.0', '1.0'],
       ['68615915.0', '4000.0', '3658.319894008867', ..., '10.0', '1.0', '2.0'],
       ['68616519.0', '21600.0', '19754.927427647883', ..., '3.0', '0.0', '2.0']], dtype='<U32')

In [169]:
#Now sav the Pre-Processed data in a proper filename
np.savetxt('loan-data-preprocessed.csv',
           loan_data,
           fmt= '%s',
           delimiter= ',')

****ADDENDUM:****
* Successfully cleaned the dataset
* Then pre-processed the dataset
* Finally, prepared the dataset for further analysis

* The Data Science team can now take this dataset and create a 'Credit Risk Model' for estimating the probability of default.

# **THE END**       